@echo off
SET PATH=%LECTEUR%CPCDOS\PILOTES\DOS;%LECTEUR%CPCDOS\SYSTEME;%LECTEUR%CPCDOS\PILOTES\RESEAU
CD > TMP.TMP
SET /P LECTEUR= < TMP.TMP
cd CPCDOS\SYSTEME
set PCIscan=1
KEYB FR
XMSDSK 102400 /y
KRNL32 RELANCE EXE/ KRNL\KRNL_DRV.CPC
